[project]
name = "python-webrtc-server"
version = "0.1.0"
description = ""
authors = [
    {name = "mtdev",email = "minhtuan.dev05@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (>=5.2.1,<6.0.0)",
    "channels (>=4.2.2,<5.0.0)",
    "channels-redis (>=4.2.1,<5.0.0)",
    "uvicorn[standard] (>=0.34.2,<0.35.0)",
]

[tool.poetry]
packages = [{include = "python_webrtc_server", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
